/**
 * Markdown format for reports
 */
import type { ComplianceReport } from '../../core/types/index.js';

/**
 * Format report as Markdown
 */
export function formatMarkdownReport(report: ComplianceReport): string {
  const lines: string[] = [];

  // Header
  lines.push('# SpecBridge Compliance Report');
  lines.push('');
  lines.push(`**Project:** ${report.project}`);
  lines.push(`**Generated:** ${new Date(report.timestamp).toLocaleString()}`);
  lines.push('');

  // Overall compliance
  lines.push('## Overall Compliance');
  lines.push('');
  lines.push(`**Score:** ${report.summary.compliance}%`);
  lines.push('');
  lines.push(formatProgressBar(report.summary.compliance));
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(
    `- **Active Decisions:** ${report.summary.activeDecisions} / ${report.summary.totalDecisions}`
  );
  lines.push(`- **Total Constraints:** ${report.summary.totalConstraints}`);
  lines.push('');

  // Violations
  lines.push('### Violations');
  lines.push('');
  const { violations } = report.summary;
  const totalViolations =
    violations.critical + violations.high + violations.medium + violations.low;

  if (totalViolations === 0) {
    lines.push('No violations found.');
  } else {
    lines.push(`| Severity | Count |`);
    lines.push(`|----------|-------|`);
    lines.push(`| Critical | ${violations.critical} |`);
    lines.push(`| High | ${violations.high} |`);
    lines.push(`| Medium | ${violations.medium} |`);
    lines.push(`| Low | ${violations.low} |`);
    lines.push(`| **Total** | **${totalViolations}** |`);
  }
  lines.push('');

  // By Decision
  if (report.byDecision.length > 0) {
    lines.push('## By Decision');
    lines.push('');
    lines.push('| Decision | Status | Constraints | Violations | Compliance |');
    lines.push('|----------|--------|-------------|------------|------------|');

    for (const dec of report.byDecision) {
      const complianceEmoji = dec.compliance >= 90 ? '✅' : dec.compliance >= 70 ? '⚠️' : '❌';
      lines.push(
        `| ${dec.title} | ${dec.status} | ${dec.constraints} | ${dec.violations} | ${complianceEmoji} ${dec.compliance}% |`
      );
    }
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push('*Generated by [SpecBridge](https://github.com/nouatzi/specbridge)*');

  return lines.join('\n');
}

function formatProgressBar(percentage: number): string {
  const width = 20;
  const filled = Math.round((percentage / 100) * width);
  const empty = width - filled;
  const filledChar = '█';
  const emptyChar = '░';

  return `\`${filledChar.repeat(filled)}${emptyChar.repeat(empty)}\` ${percentage}%`;
}
